### ISSUE TITLE
Package minimist dependency forgotten

### ISSUE THREAD

**Issue by grischard** [andrewharvey/osm-editor-layer-index-qgis#1]
`minimist` should be installed when installing oeliq.

```
> npm install -g osm-editor-layer-index-qgis

/usr/local/bin/osm-editor-layer-index-qgis -> /usr/local/lib/node_modules/osm-editor-layer-index-qgis/index.js
+ osm-editor-layer-index-qgis@1.0.0
added 2 packages from 8 contributors in 3.07s
> osm-editor-layer-index-qgis < imagery.geojson > imagery-qgis.xml
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/osm-editor-layer-index-qgis/index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
> npm install -g minimist
+ minimist@1.2.0
added 1 package from 1 contributor in 1.004s
> osm-editor-layer-index-qgis < imagery.geojson >| imagery-qgis.xml
>
```

**Comment by andrewharvey** [comment]
thanks, fixed. I'll push a patch release now.
